dependencies:
- name: redis
  version: "^3.4.1"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: queue.enabled
- name: postgresql
  version: 0.8.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled