apiVersion: v1
kind: Service
metadata:
  name: {{ .Value.env }}-sdapi
  namespace: {{ .Value.namespace }}
  labels:
    app: api
    env: {{ .Value.env }}
    tier: svc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: api
    env: {{ .Value.env }}
    tier: app
---
# requires service account to be created
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Value.env }}-sdapi
  namespace: {{ .Value.namespace }}
  labels:
    app: api
    env: {{ .Value.env }}
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      env: {{ .Value.env }}
      tier: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        env: {{ .Value.env }}
        tier: app
    spec:
      serviceAccount: sd-buildbot
      containers:
      - name: screwdriver-api
        image: {{ .Value.api.image }}
        ports:
        - containerPort: 80
          protocol: TCP
        # Validate that the service is started
        livenessProbe:
          httpGet:
            path: /v4/status
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        # Environment variables that point to your secrets in your secrets.yaml
        env:
          - name: LAUNCH_IMAGE
            value: {{ .Value.launcher.image }}
          - name: LAUNCH_VERSION
            value: {{ .Value.launcher.version }}
          - name: EXECUTOR_PLUGIN
            value: k8s
          - name: K8S_JOBS_NAMESPACE
            value: {{ .Value.namespace }}
          - name: K8S_TOKEN
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: k8stoken
          - name: DATASTORE_PLUGIN
            value: sequelize
          - name: URI
            value: {{ .Value.api.uri }}
          - name: PORT
            value: "80"
          - name: ECOSYSTEM_UI
            value: {{ .Value.ui.uri }}
          - name: ECOSYSTEM_STORE
            value: {{ .Value.store.uri }}
          - name: ECOSYSTEM_BADGES
            value: "https://badges.manhattan.corp.yahoo.com/api/v1/build/{{status}}/{{color}}"
          - name: SCM_SETTINGS
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: scmsettings
          - name: SECRET_JWT_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: jwtprivatekey
          - name: SECRET_JWT_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: jwtpublickey
          - name: SECRET_COOKIE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: cookiepassword
          - name: DATASTORE_SEQUELIZE_DIALECT
            value: postgres
          - name: DATASTORE_SEQUELIZE_HOST
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: postgreshost
          - name: DATASTORE_SEQUELIZE_PREFIX
            value: "{{ .Value.env }}-"
          - name: DATASTORE_SEQUELIZE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgrespassword
                name: screwdriver-api-{{ .Value.env }}-secrets
          - name: DATASTORE_SEQUELIZE_PORT
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: postgresport
          - name: DATASTORE_SEQUELIZE_USERNAME
            valueFrom:
              secretKeyRef:
                key: postgresusername
                name: screwdriver-api-{{ .Value.env }}-secrets
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: encryptionpassword
          - name: SECRET_HASHING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: screwdriver-api-{{ .Value.env }}-secrets
                key: hashingpassword
          {{- if .Values.notifications.enabled }}
          - name: NOTIFICATIONS
            valueFrom:
              secretKeyRef:
                key: notifications
                name: screwdriver-api-{{ .Value.env }}-secrets
          {{- end }}
          - name: SECRET_WHITELIST
            value: '[]'
          - name: ECOSYSTEM_ALLOW_CORS
            valueFrom:
              secretKeyRef:
                key: allowcors
                name: screwdriver-api-{{ .Value.env }}-secrets