---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: enc-gp2
  labels:
    k8s-addon: storage-aws.addons.k8s.io
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  kmsKeyId: {{ .Values.storageClass.kmsKeyId }}
  encrypted: 'true'